//This would probably make more sense as a SQL table but github.io doesn't support PHP so here we are.

var factionList = [
	//	0
	{
		name			: "Agents of Mistmoore",
		era				: 0,
		importance		: 0,
		allies			: [101],
		enemies			: null,
		description		: "Servants of the famous vampire found in his Faydwer castle, as well as his Drachnid agents in Kunark.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	1
	{
		name			: "Aggressors of Kithicor",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	2
	{
		name			: "Allize Taeew",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Cannibalistic lizardmen found in the Feerrott.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	3
	{
		name			: "Allize Volew",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [2],
		description		: "One of two clans of Lizardmen found in the Feerrott and Rathe Mountains.",
		howToRaise		: "Slaughter the rival lizardmen of the Tae Ew clan, found throughout the Feerrott.",
		factionsLowered	: [2],
	},
	//	4
	{
		name			: "Anchorites of Brell Serilis",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Gnoll worshippers of Brell Serilis found in the Jaggedpine Forest",
		howToRaise		: "Complete the quest <a href='http://everquest.allakhazam.com/db/quest.html?quest=2176'>Snarla's friendship</a>.",
		factionsLowered	: null,
	},
	//	5
	{
		name			: "Ankhefenmut",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [180],
		description		: "A sphinx and her scarab followers found in Rathe Mountains.",
		howToRaise		: "Kill the rival sphinx Zazamoukh and her followers.",
		factionsLowered	: [180],
	},
	//	6
	{
		name			: "Antonius Bayle",
		era				: 0,
		importance		: 2,
		allies			: [70,111],
		enemies			: [81,202],
		description		: "The leader of the city of Qeynos and some of his agents.",
		howToRaise		: "Many quests in Qeynos will increase this faction. The easiest repeatable way is probably <a href='http://everquest.allakhazam.com/db/quest.html?quest=574'>giving bone chips to Lashun Novashine</a>.",
		factionsLowered	: [11],
	},
	//	7
	{
		name			: "Arboreans of the Faydark",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [55,155,60,171],
		description		: "Small treants found in the greater Faydark. This faction is listed as Unimportant as it starts out non-KOS, but killing them does give boosts to some Kelethin factions so you may wish to treat this faction as expendable.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	8
	{
		name			: "Arcane Scientists",
		era				: 0,
		importance		: 2,
		allies			: [96],
		enemies			: [124,167],
		description		: "Freeport's spellcaster guild. Unfortunately it is not one of the factions increased by the PoR Freeport faction missions, so you'll still have to work on this faction the old fashioned way.",
		howToRaise		: "The only way to improve this faction is by doing their quests. <a href='http://everquest.allakhazam.com/db/quest.html?quest=679'>Rat Ear Pie</a> is an easy one that can be done with store bought ingredients.",
		factionsLowered	: [124,167],
	},
	//	9
	{
		name			: "Ashen Order",
		era				: 0,
		importance		: 2,
		allies			: [96,153],
		enemies			: null,
		description		: "Freeport's monk guild.",
		howToRaise		: "Slaughter Deathfist orcs around Freeport. If you get tired of killing orcs the sash quests also provide a decent faction boosts, but require having enough faction to start.",
		factionsLowered	: [40],
	},
	//	10
	{
		name			: "Befallen Inhabitants",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Undead found within Befallen.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	11
	{
		name			: "Bloodsabers",
		era				: 0,
		importance		: 2,
		allies			: [124,29],
		enemies			: [135,70],
		description		: "Necromancers and shadowknights operating out of the catacombs under Qeynos.",
		howToRaise		: "The easiest way to raise Bloodsaber faction is to slaughter the sacred koalindl fish in the pools around the Temple of Life. However, doing so will ruin your faction with several good Qeynos factions. If you want to preserve those factions you can <a href='http://everquest.allakhazam.com/db/quest.html?quest=2255'>buy Blackburrow Stout</a> from Guard Shilter in North Karana, which raises several evil Qeynos factions and only hurts Guards of Qeynos.",
		factionsLowered	: [70],
	},
	//	12
	{
		name			: "Broken Skull Clan",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [148,35],
		description		: "A band of troll pirates. Note that this does not include the Broken Skull Pirates in LoY zones. There is no way to raise this faction without hurting DaBashers faction so you'll have to pick one or the other. As this faction includes only 2 NPCs and one quest DaBashers are probably the better choice.",
		howToRaise		: "Kill troll bashers.",
		factionsLowered	: [35],
	},
	//	13
	{
		name			: "Brownies of Faydwer",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Brownies found in the Faydark forest.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	14
	{
		name			: "Burning Dead",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Necromancers and shadowknights found within Befallen.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	15
	{
		name			: "Butcherblock Bandits",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [114,162],
		description		: "Dwarven bandits preying on travelers in the Butcherblock Mountains.",
		howToRaise		: "The only way to raise this faction is to kill members of the Kaladim rogue guild, Miners Guild 628. While this has the added benefit of boosting your standing with the Qeynos and Neriak guilds, it will also hurt your standing with the Rivervale rogue guild.",
		factionsLowered	: [114,42],
	},
	//	16
	{
		name			: "Carson McCabe",
		era				: 0,
		importance		: 0,
		allies			: [77,108,27],
		enemies			: [202],
		description		: "The leader of Highkeep.",
		howToRaise		: "This faction can be raised a few different ways but the easiest way that won't hurt other factions is <a href='http://everquest.allakhazam.com/db/quest.html?quest=262'>turning in scaps in Highpass</a>.",
		factionsLowered	: null,
	},
	//	17
	{
		name			: "Circle of Unseen Hands",
		era				: 0,
		importance		: 2,
		allies			: [29,81],
		enemies			: [70,111],
		description		: "The Qeynos rogues guild. This faction has connections to many other Qeynos factions as well as rogue guilds in other cities, meaning many quests or kills in classic affect it one way or the other.",
		howToRaise		: "There are quite a few options, but I recommend <a href='http://everquest.allakhazam.com/db/quest.html?quest=2255'>buying Blackburrow Stout</a> from Guard Shilster in North Karana. If you don't want to have to repair your Guards of Qeynos standing you can also kill Karana bandits.",
		factionsLowered	: [70,82],
	},
	//	18
	{
		name			: "Citizens of Gukta",
		era				: 0,
		importance		: 2,
		allies			: [139,75,100,71],
		enemies			: null,
		description		: "Froglok citizens.",
		howToRaise		: "Deliver bone chips or fish to <a href='http://everquest.allakhazam.com/db/quest.html?quest=2318'>Dar Collector Reokar</a>.",
		factionsLowered	: null,
	},
	//	19
	{
		name			: "Clan Kolbok",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: [76,73],
		description		: "Kobolds found in The Warrens and Stonebrunt Mountains. Fighting them is a good way to earn faction with both Erudite cities.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	20
	{
		name			: "Clan Runnyeye",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [93,162,163,69],
		description		: "One of the two clans of goblins living in Runnyeye and the surrounding zones.",
		howToRaise		: "The easiest way to raise this faction is to kill King Xorbb and his followers. However, if you want to max unimportant factions then you will instead need to kill Mayor Gubbin. This will harm several Rivervale factions, but those can be repaired, and it's impossible to max Runnyeye, Pickclaw, and King Xorbb at the same time otherwise.",
		factionsLowered	: [69,102,112,137],
	},
	//	21
	{
		name			: "Clerics of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Clerics of the Froglok city of Gukta.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	22
	{
		name			: "Clerics of Tunare",
		era				: 0,
		importance		: 2,
		allies			: [92],
		enemies			: null,
		description		: "Felwithe cleric guild.",
		howToRaise		: "<a href='http://everquest.allakhazam.com/db/quest.html?quest=91'>Give bone chips</a> to Yeolarn Bronzeleaf.",
		factionsLowered	: null,
	},
	//	23
	{
		name			: "Clerics of Underfoot",
		era				: 0,
		importance		: 2,
		allies			: [84,113],
		enemies			: null,
		description		: "Kaladim cleric Guild.",
		howToRaise		: "Deliver <a href='http://everquest.allakhazam.com/db/quest.html?quest=366'>bone chips</a> to Gunlok Jure.",
		factionsLowered	: null,
	},
	//	24
	{
		name			: "Clockworks of Ak'Anon",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	25
	{
		name			: "Clurg",
		era				: 0,
		importance		: 2,
		allies			: [31,65,122],
		enemies			: [84],
		description		: "The leader of the ogre city of Oggok.",
		howToRaise		: "Doing quests for many Oggok factions will give allied hits for Clurg, but the only option that doesn't hurt other factions is to do quests for Oggok Guards, such as <a href='http://everquest.allakhazam.com/db/quest.html?quest=2473'>vermin extermination</a>.",
		factionsLowered	: null,
	},
	//	26
	{
		name			: "Coalition of Tradefolk",
		era				: 0,
		importance		: 2,
		allies			: [27,96,111],
		enemies			: null,
		description		: "Merchants of Freeport.",
		howToRaise		: "Do the Citizens of Freeport missions introduced in Prophecy of Ro.",
		factionsLowered	: null,
	},
	//	27
	{
		name			: "Coalition of Tradefolk Underground",
		era				: 0,
		importance		: 2,
		allies			: [16,26,29,167],
		enemies			: null,
		description		: "Freeport's rogue guild and illicit merchants. Formerly called Coalition of Tradefolk Illegal.",
		howToRaise		: "Deliver Tumpy Tonics to <a href='http://everquest.allakhazam.com/db/quest.html?quest=130'>Groflah Steadirt</a>. The tonics must be crafted but <a href='http://www.eqtraders.com/items/show_item.php?item=4968&menustr=035000000000'>the recipe</a> is not terribly difficult and uses vendor bought components.",
		factionsLowered	: null,
	},
	//	28
	{
		name			: "Commons Residents",
		era				: 0,
		importance		: 2,
		allies			: [96,136,167],
		enemies			: null,
		description		: "Residents of the Commonlands.",
		howToRaise		: "Kill Deathfist Orcs.",
		factionsLowered	: [40],
	},
	//	29
	{
		name			: "Corrupt Qeynos Guards",
		era				: 0,
		importance		: 2,
		allies			: [11,17,81],
		enemies			: [70],
		description		: "Corrupt Guards who support Kane Bayle. Note that though this faction and the non-corrupt guards are enemies, the good guards don't know who's corrupt so they will assist NPCs on this faction.",
		howToRaise		: "Turn in <a href='http://everquest.allakhazam.com/db/quest.html?quest=262'>scalps</a> in Highpass.",
		factionsLowered	: null,
	},
	//	30
	{
		name			: "Craftkeepers",
		era				: 0,
		importance		: 2,
		allies			: [74,76],
		enemies			: [73],
		description		: "Erudin's enchanter guild.",
		howToRaise		: "This faction has a couple of quests, but you'll probably find it far easier to head to Paineel and slaughter heretics.",
		factionsLowered	: [73],
	},
	//	31
	{
		name			: "Craknek Warriors",
		era				: 0,
		importance		: 2,
		allies			: [25],
		enemies			: [65],
		description		: "Oggok warrior guild. Doing quests for this faction directly will hurt your Greenblood Knights faction. However, you can repair both this faction and Greenblood Knights by helping Clurg, at the expense of Kazon Stormhammer faction. Since repairing your Greenblood Knight faction would require damaging Kaladim factions anyway you might as well take the Clurg route.",
		howToRaise		: "Bring pickled froglok to <a href='http://everquest.allakhazam.com/db/quest.html?quest=290'>Chef Dooga</a>.",
		factionsLowered	: [84],
	},
	//	32
	{
		name			: "Crimson Hands",
		era				: 0,
		importance		: 2,
		allies			: [74,76],
		enemies			: [73],
		description		: "Erudin's wizard guild.",
		howToRaise		: "There are a few quests for this faction but you might find it easier to head to Paineel and slaughter heretics.",
		factionsLowered	: [73],
	},
	//	33
	{
		name			: "Crushbone Orcs",
		era				: 0,
		importance		: 1,
		allies			: [78],
		enemies			: [55,60,162],
		description		: "A notorious clan of orcs found in Faydwer. It's possible to raise this faction but doing so will upset quite a few Kelethin factions. Repairing those factions without hurting this faction will prove difficult, so you may want to treat this faction as expendable unless you're roleplaying a Neriak aligned character.",
		howToRaise		: "Kill members of the wood elf ranger guild.",
		factionsLowered	: [22,60,92,155],
	},
	//	34
	{
		name			: "Cursed Frogloks of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	35
	{
		name			: "DaBashers",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [12],
		description		: "Grobb warrior guild. It is impossible to raise this faction without hurting Broken Skull Clan and vice versa, but as the other has only 2 NPCs and one quest this is the more useful faction.",
		howToRaise		: "Bring fire beetle eyes to <a href='http://everquest.allakhazam.com/db/quest.html?quest=3543'>Basher Nanrum</a>.",
		factionsLowered	: [12],
	},
	//	36
	{
		name			: "Dark Bargainers",
		era				: 0,
		importance		: 2,
		allies			: [50,51],
		enemies			: null,
		description		: "Merchants of Neriak. This faction is quite useful as it provides an easy way to raise both Dread Guard factions without harming any others.",
		howToRaise		: "Give red wine to <a href='http://everquest.allakhazam.com/db/quest.html?quest=159'>Lokar To'Biath</a>",
		factionsLowered	: null,
	},
	//	37
	{
		name			: "Dark Ones",
		era				: 0,
		importance		: 2,
		allies			: [148],
		enemies			: [61],
		description		: "Shaman and beastlord guild in Grobb.",
		howToRaise		: "Do quests for guild members, such as their <a href='http://everquest.allakhazam.com/db/quest.html?quest=1474'>armor quest</a>.",
		factionsLowered	: [61],
	},
	//	38
	{
		name			: "Dark Reflection",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [41,54,63],
		description		: "The gnome necromancer guild. In place of doing their quests you can kill members of the Eldritch Collective, which will hurt different factions but has the benefit of giving faction with The Dead.",
		howToRaise		: "Complete their quests, such as <a href='http://everquest.allakhazam.com/db/quest.html?quest=728'>this one</a>.",
		factionsLowered	: [41,54,63],
	},
	//	39
	{
		name			: "Darkpaws of Jaggedpine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: [80,140,143],
		description		: "Darkpaw gnolls found in the Jaggedpine Forest. Not to be confused with the Darkpaw Gnolls faction, a quest faction in Oceangreen Hills. Fighting this expendable faction is a great way to boost some nearby factions without hurting anything important.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	40
	{
		name			: "Deathfist Orcs",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: [9,28,69,96],
		description		: "Orcs found in areas around Freeport and Rivervale. Fighting this expendable faction is a decent way to improve a few Freeport and Rivervale factions.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	41
	//TODO: How to raise
	{
		name			: "Deepmuses",
		era				: 0,
		importance		: 2,
		allies			: [63,104],
		enemies			: [38],
		description		: "Clerics and rogues of Ak'Anon",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	42
	//TODO: How to raise
	{
		name			: "Deeppockets",
		era				: 0,
		importance		: 2,
		allies			: [16,17,27],
		enemies			: [112],
		description		: "Rivervale's rogue guild. Also includes some  goblins.",
		howToRaise		: "Deliver bandages to <a href='http://everquest.allakhazam.com/db/quest.html?quest=657'>to Joogl Honeybugger</a>.",
		factionsLowered	: [27],
	},
	//	43
	{
		name			: "Deepwater Knights",
		era				: 0,
		importance		: 2,
		allies			: [74],
		enemies			: [73],
		description		: "Erudin's paladin guild.",
		howToRaise		: "Kill Heretics in Paineel.",
		factionsLowered	: [73],
	},
	//	44
	{
		name			: "Defective Clockwork",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "Rogue clockworks in the area around Ak'Anon.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	45
	{
		name			: "Defenders of Kithicor",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	46
	{
		name			: "Dervish Cutthroats",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "Bandits in the Desert of Ro.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	47
	{
		name			: "Dismal Rage",
		era				: 0,
		importance		: 2,
		allies			: [124],
		enemies			: [96],
		description		: "Freeport's necromancers and shadowknights. You probably won't need to do much for this faction as you're likely to max it in the process of working on Opal Darkbriar. However, if you need to it's easy to improve this faction with the missions added in Prophecy of Ro.",
		howToRaise		: "Do the Citizens of Freeport quests and missions introduced in PoR.",
		factionsLowered	: null,
	},
	//	48
	{
		name			: "Donovon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	49
	{
		name			: "Drafling",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "A mysterious dragon halfling.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	50
	{
		name			: "Dreadguard Inner",
		era				: 0,
		importance		: 2,
		allies			: [36,51,78],
		enemies			: [138],
		description		: "Guards deeper within Neriak. They are less tolerant of other races than the foreign quarter guards.",
		howToRaise		: "Give red wine to <a href='http://everquest.allakhazam.com/db/quest.html?quest=159'>Lokar To'Biath</a>",
		factionsLowered	: null,
	},
	//	51
	{
		name			: "Dreadguard Outer",
		era				: 0,
		importance		: 2,
		allies			: [36,50,78],
		enemies			: [55],
		description		: "Guards in the Neriak Commons. They are more tolerant of other races than the guards in the innermost parts of Neriak.",
		howToRaise		: "Give red wine to <a href='http://everquest.allakhazam.com/db/quest.html?quest=159'>Lokar To'Biath</a>",
		factionsLowered	: null,
	},
	//	52
	{
		name			: "Dryads of the Grove",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "Dryads in Jaggedpine Forest.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	53
	//TODO: How to raise
	{
		name			: "Ebon Mask",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [16,69,70,179],
		description		: "Neriak rogue guild.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	54
	//TODO: How to raise
	{
		name			: "Eldritch Collective",
		era				: 0,
		importance		: 2,
		allies			: [63,90],
		enemies			: [38,166],
		description		: "Ak'Anon caster guild.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	55
	{
		name			: "Emerald Warriors",
		era				: 0,
		importance		: 2,
		allies			: [87,106],
		enemies			: [78],
		description		: "Kelethin's guard faction and warrior guild. Opposed to the Neriak warrior guild, but thankfully you can raise this faction without harming any important factions by killing aqua goblins.",
		howToRaise		: "Hunt Riptide aqua goblins in Butcherblock Mountains and Lake Rathetear.",
		factionsLowered	: [144],
	},
	//	56
	{
		name			: "Erudin Citizens",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Citizens of the Erudite city.",
		howToRaise		: "Repeat <a href='http://everquest.allakhazam.com/db/quest.html?quest=131'>this quest.</a>",
		factionsLowered	: null,
	},
	//	57
	{
		name			: "Exiled Frogloks",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Froglok exiles in Innothule Swamp.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	58
	{
		name			: "Fairie",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Fairies found in Lesser Faydark. While raising this faction is doable, it will give smaller hits to other factions as you will have to do multiple quest turn ins to get the item you ultimately need for Fairie faction.",
		howToRaise		: "Repeat <a href='http://everquest.allakhazam.com/db/quest.html?quest=92'>this quest.</a> You don't need to do the whole quest, just repair Sanfyrd's toupee so you get the fairie wing to give to Princess Joleena.",
		factionsLowered	: [38,130],
	},
	//	59
	{
		name			: "Fallen of Bloody Kithicor",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "The undead of Kithicor Forest. The notorious band of Dark Elves are also in this faction.",
		howToRaise		: "Kill Stanos Herkanor and <a href='http://everquest.allakhazam.com/db/quest.html?quest=1257'>turn in his head</a>.",
		factionsLowered	: [16,29,77,108,167],
	},
	//	60
	//TODO: How to increase
	{
		name			: "Faydarks Champions",
		era				: 0,
		importance		: 2,
		allies			: [22,92,155],
		enemies			: [33],
		description		: "Kelethin's ranger guild.",
		howToRaise		: "The easiest way is to <a href='http://everquest.allakhazam.com/db/quest.html?quest=611'> give muffins to Pandos</a>. This will hurt your Crushbone Orcs faction, so if you care about that faction you can do <a href='http://everquest.allakhazam.com/db/quest.html?quest=158'>this quest</a> instead.",
		factionsLowered	: null,
	},
	//	61	
	{
		name			: "Frogloks of Guk",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "Frogloks living in Guk, not to be confused with the Guktan frogloks.",
		howToRaise		: "Kill undead frogloks in Lower Guk. Alternately you can kill Frogloks in Sebilis, which will also hurt Trakanon faction but raise Frogloks of Krup and Legion of Cabilis.",
		factionsLowered	: [172],
	},
	//	62
	{
		name			: "Gate Callers",
		era				: 0,
		importance		: 2,
		allies			: [74,76],
		enemies			: [73],
		description		: "Erudin's magician guild.",
		howToRaise		: "Head to Paineel and kill Heretics.",
		factionsLowered	: [73],
	},
	//	63
	{
		name			: "Gem Choppers",
		era				: 0,
		importance		: 2,
		allies			: [90,104],
		enemies			: [38,216],
		description		: "Ak'Anon warrior guild.",
		howToRaise		: "Kill Riptide aqua goblins.",
		factionsLowered	: [144],
	},
	//	64
	{
		name			: "Goblins of Fire Peak",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [170],
		description		: "Fire Goblins living in Lavastorm and the adjacent caverns. Diametrically opposed to Tribe Vrodak. You can raise one or the other but not both.",
		howToRaise		: "Kill kobolds of Tribe Vrodak.",
		factionsLowered	: [170],
	},
	//	65
	{
		name			: "Green Blood Knights",
		era				: 0,
		importance		: 2,
		allies			: [25],
		enemies			: [148,162],
		description		: "Oggok shadowknight guild.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	66
	{
		name			: "Grobb Guard",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "Troll prisoners in Guk. Not actually guards of Grobb.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	67
	{
		name			: "Grobb Merchants",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Merchants of Grobb.",
		howToRaise		: "Complete Grobb's <a href='http://everquest.allakhazam.com/db/faction.html?faction=283'> vermin extermination</a>.",
		factionsLowered	: null,
	},
	//	68
	{
		name			: "Guardians of the Hatchling",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	69	
	{
		name			: "Guardians of the Vale",
		era				: 0,
		importance		: 2,
		allies			: [102,112,163],
		enemies			: [51],
		description		: "Rivervale's guards.",
		howToRaise		: "Kill Stone Hive bixies or Deathfist Orcs.",
		factionsLowered	: [40,161],
	},
	//	70
	{
		name			: "Guards of Qeynos",
		era				: 0,
		importance		: 2,
		allies			: [6,111],
		enemies			: [17,29],
		description		: "Guards of the city of Qeynos. This faction is either an ally or enemy of virtually every faction in Qeynos and the surrounding zones, making it easy to raise but also easy to hurt. Beware, even though they are mutual enemies with the Corrupt Qeynos Guards, the loyal guards don't know who is corrupt and will assist corrupt guards.",
		howToRaise		: "The traditional way to improve this faction is to lay waste to Blackburrow. However, Sabertooths of Blackburrow faction can't be improved without hurting this faction, so if you're a completionist who wants to keep unimportant factions or just has a soft spot for the gnolls you can kill Karana Bandits instead. Alternately, you can do quests for certain allied factions with no enemies such as Silent Fist Clan or Karana Residents.",
		factionsLowered	: [82],
	},
	//	71
	{
		name			: "Guktan Elders",
		era				: 0,
		importance		: 2,
		allies			: [75,100,139],
		enemies			: null,
		description		: "Elders of Gukta.",
		howToRaise		: "Assist <a href='http://everquest.allakhazam.com/db/quest.html?quest=2318'>Dar Collector Reokar</a>.",
		factionsLowered	: null,
	},
	//	72
	{
		name			: "Guktan Suppliers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	73
	{
		name			: "Heretics",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [30,32,43,62],
		description		: "Erudites living in the city of Paineel. You will likely ruin your standing with them while improving Erudin factions, but fortunately this faction can be repaired without harming Erudin factions by fighting kobolds.",
		howToRaise		: "Kill kobolds in The Warrens and Stonebrunt Mountains.",
		factionsLowered	: [19],
	},
	//	74
	{
		name			: "High Council of Erudin",
		era				: 0,
		importance		: 2,
		allies			: [76],
		enemies			: [73,89,202],
		description		: "The leaders of Erudin.",
		howToRaise		: "Give Capt. Orlin's Spiced Ale to Palatos Kynarn as part of <a href='http://everquest.allakhazam.com/db/quest.html?quest=384'>this quest</a>. You can complete the whole quest for additional faction but it's faster to just turn in stacks of ale.",
		factionsLowered	: [73],
	},
	//	75
	//TODO: Allies and enemies
	{
		name			: "High Council of Gukta",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "The leaders of Gukta. Unsure of allies and enemies as I haven't found NPCs actually on this faction.",
		howToRaise		: "Assist <a href='http://everquest.allakhazam.com/db/quest.html?quest=2318'>Dar Collector Reokar</a>.",
		factionsLowered	: null,
	},
	//	76
	{
		name			: "High Guard of Erudin",
		era				: 0,
		importance		: 2,
		allies			: [74,105],
		enemies			: [73,89],
		description		: "Erudin guards.",
		howToRaise		: "Kill kobolds in The Warrens and Stonebrunt Mountains.",
		factionsLowered	: [19],
	},
	//	77
	{
		name			: "Highpass Guards",
		era				: 0,
		importance		: 2,
		allies			: [16,29,108,167],
		enemies			: null,
		description		: "Guards of Highpass.",
		howToRaise		: "Hunt the Shralok Orcs and Mucktail gnolls in Highpass and the adjacent zones. Turn in their scalps for an extra boost.",
		factionsLowered	: [116,152],
	},
	//	78
	//TODO: How to raise
	{
		name			: "Indigo Brotherhood",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [55,138,160],
		description		: "Neriak warrior guild.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	79
	{
		name			: "Inhabitants of Hate",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Denizens of the Plane of Hate.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	80
	{
		name			: "Jaggedpine Treefolk",
		era				: 0,
		importance		: 2,
		allies			: [70,140,164],
		enemies			: [173],
		description		: "Qeynos druid guild based in Surefall Glade.",
		howToRaise		: "Kill Darkpaw gnolls in Jaggedpine Forest.",
		factionsLowered	: [39],
	},
	//	81
	//TODO: Allies and enemies
	{
		name			: "Kane Bayle",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "The commander of the Qeynos guard and brother of Antonius Bayle. Secretly the leader of the corrupt guards and in league with the Bloodsabers. Unsure of allies and enemies as Kane himself, as a guildmaster, can't be killed, nor does he have quests, and no other NPCs appear to be on this faction.",
		howToRaise		: "Buy Blackburow Stout from <a href='http://everquest.allakhazam.com/db/quest.html?quest=2255'>Guard Shilster'</a>.",
		factionsLowered	: [70],
	},
	//	82
	{
		name			: "Karana Bandits",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [17,70,77,83],
		description		: "Bandits and brigands in the Plains of Karana.",
		howToRaise		: "Kill Mucktail Gnolls",
		factionsLowered	: [116],
	},
	//	83
	{
		name			: "Karana Residents",
		era				: 0,
		importance		: 2,
		allies			: [70,95,135],
		enemies			: null,
		description		: "Farmers and other residents of the Plains of Karana. As they have no enemies, doing quests for them is a good way to raise faction with their allies without hurting their respective enemies.",
		howToRaise		: "Kill Mucktail Gnolls",
		factionsLowered	: [116],
	},
	//	84
	{
		name			: "Kazon Stormhammer",
		era				: 0,
		importance		: 2,
		allies			: [162],
		enemies			: [25,101,202],
		description		: "The ruler of Kaladim.",
		howToRaise		: "Deliver <a href='http://everquest.allakhazam.com/db/quest.html?quest=366'>bone chips</a> to Gunlok Jure.",
		factionsLowered	: null,
	},
	//	85
	{
		name			: "Keepers of the Arts",
		era				: 0,
		importance		: 2,
		allies			: [60,92],
		enemies			: [166],
		description		: "Felwithe caster guild.",
		howToRaise		: "Give bat wings to <a href='http://everquest.allakhazam.com/db/quest.html?quest=89'>Niola Impholder</a>.",
		factionsLowered	: [166],
	},
	//	86
	{
		name			: "Kejek Village",
		era				: 0,
		importance		: 2,
		allies			: [129],
		enemies			: null,
		description		: "Kejek living in Stonebrunt Mountains.",
		howToRaise		: "Complete their quests, such as <a href='http://everquest.allakhazam.com/db/quest.html?quest=2906'>this one</a>.",
		factionsLowered	: null,
	},
	//	87
	{
		name			: "Kelethin Merchants",
		era				: 0,
		importance		: 2,
		allies			: [55,60],
		enemies			: null,
		description		: "Merchants of Kelethin.",
		howToRaise		: "The easiest way is to give wine to Lady Shae, but this will hurt your Indigo Brotherhood faction. If you prefer not to do that you can do <a href='http://everquest.allakhazam.com/db/quest.html?quest=2906'>this quest</a> instead. Killing Crushbone orcs would also hurt Indigo Brotherhood, but you can get around that by buying them or just use Deathfist items instead.",
		factionsLowered	: null,
	},
	//	88
	{
		name			: "Kerra Isle",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Kerrans living in the Toxxulia Forest. Somewhat at odds with the Erudites.",
		howToRaise		: "Do various quests for them. None stand out as exceptionally easy.",
		factionsLowered	: null,
	},
	//	89
	{
		name			: "Kerra of Barren Coast",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "Kerrans living along the Barren Coast. As they don't appear to give faction hits when killed their allies and enemies cannot be determined.",
		howToRaise		: "Kill members of High Council of Erudin, such as <a href='http://everquest.allakhazam.com/db/npc.html?id=12406'>Malik Zaren</a>. You can also kill Erudin Sentinels, which gives you far more options, but will ruin your Merchants of Erudin faction as well.",
		factionsLowered	: [74,76],
	},
	//	90
	{
		name			: "King Ak'Anon",
		era				: 0,
		importance		: 2,
		allies			: [54,63],
		enemies			: [38,103],
		description		: "The ruler of Ak'Anon.",
		howToRaise		: "Kill minotaurs, brownies, and other servants of Meldrath in Steamfont. If you want to align yourself with Meldrath and his gang  you can instead do quests for allied factions in Ak'Anon, but this is likely to hurt your standing with other factions like The Dead and Dark Reflection.",
		factionsLowered	: [103],
	},
	//	91
	{
		name			: "King Naythox Thex",
		era				: 0,
		importance		: 1,
		allies			: [78],
		enemies			: [92,218,166],
		description		: "The king of the dark elves. Opposed to the dark elf queen and her necromancer followers.",
		howToRaise		: "There are two ways to raise this faction: fight members of the dark elf necromancer faction, The Dead, or do quests for the Priests of Innoruuk, which will hurt standing with the cleric guilds of several other cities. While fighting the Dead does have the advantage of raising other factions and only lowers that faction and the unimportant Queen Cristanos faction, it's a difficult faction to repair so you might find it preferable to go the priests route.",
		factionsLowered	: [22,135,136],
	},
	//	92
	{
		name			: "King Tearis Thex",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "The king of Felwithe, and father of the famous Firiona Vie. This faction is listed as Unimportant as it doesn't appear to have any quests or NPCs associated with it. As it has no NPCs or quests allies and enemies cannot be determined.",
		howToRaise		: "<a href='http://everquest.allakhazam.com/db/quest.html?quest=91'>Give bone chips</a> to Yeolarn Bronzeleaf.",
		factionsLowered	: null,
	},
	//	93
	{
		name			: "King Xorbb",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [20,131],
		description		: "The ruler of Beholder's Maze and his followers.",
		howToRaise		: "Fight Pickclaw or Runnyeye goblins. Note that fighting this faction is the only way to raise Pickclaw faction, while Runnyeye can be raised other ways, albeit at the cost of mutliple Rivervale factions.",
		factionsLowered	: [20],
	},
	//	94
	{
		name			: "Kithicor Residents",
		era				: 0,
		importance		: 2,
		allies			: [80,140],
		enemies			: [173],
		description		: "Residents of the cursed forest of Kithicor.",
		howToRaise		: "Hunt Shralok orcs.",
		factionsLowered	: [152],
	},
	//	95
	{
		name			: "Knights of Thunder",
		era				: 0,
		importance		: 2,
		allies			: [70,135],
		enemies			: [11],
		description		: "Clerics and paladins in Qeynos who worship Karana.",
		howToRaise		: "There are no mobs you can kill for this faction, but there are numerous quests. The easiest repeatable way is probably <a href='http://everquest.allakhazam.com/db/quest.html?quest=574'>giving bone chips to Lashun Novashine</a>.",
		factionsLowered	: [11],
	},
	//	96
	{
		name			: "Knights of Truth",
		era				: 0,
		importance		: 2,
		allies			: [136,160],
		enemies			: [47,167],
		description		: "Freeport paladin guild. Famously opposed to the Freeport militia.",
		howToRaise		: "Do the Citizens of Freeport missions introduced in Prophecy of Ro. If on a server without PoR then kill Deathfist orcs.",
		factionsLowered	: null,
	},
	//	97
	{
		name			: "Kobolds of Fire Pit",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: [156],
		description		: "Kobolds found in Solusek's Eye and Nagafen's Lair.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	98
	{
		name			: "Krag",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Aviaks found in the Butcherblock Mountains.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	99
	{
		name			: "League of Antonican Bards",
		era				: 0,
		importance		: 2,
		allies			: [70,96],
		enemies			: [101,202],
		description		: "The human and half elf bard guild. They have guild halls in the major human cities, but individual members are found in cities throughout the world. They are part of a 3 way conflict with Mayong Mistmoore and the Ring of Scale.",
		howToRaise		: "Fight in Mistmoore Castle.",
		factionsLowered	: [0,101],
	},
	//	100
	{
		name			: "Lorekeepers of Gukta",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "A faction of Guktan frogloks. It is unclear if any NPCs actually use this faction, so allies and enemies can't be determined.",
		howToRaise		: "Deliver bone chips or fish to <a href='http://everquest.allakhazam.com/db/quest.html?quest=2318'>Dar Collector Reokar</a>.",
		factionsLowered	: null,
	},
	//	101
	{
		name			: "Mayong Mistmoore",
		era				: 0,
		importance		: 1,
		allies			: [0],
		enemies			: [92,99,202],
		description		: "The famous vampire of Lesser Faydark.",
		howToRaise		: "While the easiest way to raise this faction is to slaughter the Ring of Scale, it's impossible to repair the latter faction without harming this one. If you want to presever as many factions as possible the best route for this faction is fight Drusella Sathir and her followers in Howling Stones. This will hurt Venril Sathir faction, but that can be repaired.",
		factionsLowered	: [189,215],
	},
	//	102
	{
		name			: "Mayor Gubbin",
		era				: 0,
		importance		: 2,
		allies			: [69,112,137],
		enemies			: [20],
		description		: "The mayor of Rivervale",
		howToRaise		: "Deliver bandages to <a href='http://everquest.allakhazam.com/db/quest.html?quest=657'>to Joogl Honeybugger</a>.",
		factionsLowered	: [27],
	},
	//	103
	{
		name			: "Meldrath",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [63,90],
		description		: "The infamous gnome and his followers in Steamfont Mountains.",
		howToRaise		: "Kill NPCs on King Ak'Anon faction. Aside from the king himself, this includes a few other gnomes and a number of clockworks around the city.",
		factionsLowered	: [54,63,90],
	},
	//	104
	{
		name			: "Merchants of Ak'Anon",
		era				: 0,
		importance		: 2,
		allies			: [41,63,90],
		enemies			: null,
		description		: "Merchants of the gnome city in Faydwer.",
		howToRaise		: "Deliver <a href='http://everquest.allakhazam.com/db/quest.html?quest=3548'>Vasty Deep Ale to Shondo Billin</a>.",
		factionsLowered	: [217,38],
	},
	//	105
	{
		name			: "Merchants of Erudin",
		era				: 0,
		importance		: 2,
		allies			: [74,76],
		enemies			: null,
		description		: "Mercants of the Erudite city on Odus.",
		howToRaise		: "Deliver Wooden Shards to Emil Parsini as part pf <a href='http://everquest.allakhazam.com/db/quest.html?quest=149'>this quest</a>. The shards are dropped by treants, but you might find it easier to get them by giving Small Lanterns to Jyle Windshot as part of <a href='http://everquest.allakhazam.com/db/quest.html?quest=178'>this quest</a>. The turn in will damage your Crushbone Orc standing, but the shards are tradeable so this can be done on an alt to avoid the negative hit if desired.",
		factionsLowered	: null,
	},
	//	106
	{
		name			: "Merchants of Felwithe",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Merchants of the high elf city in Faydwer.",
		howToRaise		: "Deliver <a href='http://everquest.allakhazam.com/db/quest.html?quest=4304'>wine to Lady Shae</a>.",
		factionsLowered	: [78],
	},
	//	107
	{
		name			: "Merchants of Halas",
		era				: 0,
		importance		: 2,
		allies			: [150,179],
		enemies			: null,
		description		: "Merchants of the barbarian city in Northern Antonica.",
		howToRaise		: "Deliver <a href='http://everquest.allakhazam.com/db/quest.html?quest=224'>polar bear skins</a> or <a href='http://everquest.allakhazam.com/db/quest.html?quest=717'>wratch orc wristbands</a> to Cindl.",
		factionsLowered	: null,
	},
	//	108
	{
		name			: "Merchants of Highpass",
		era				: 0,
		importance		: 2,
		allies			: [16,77],
		enemies			: null,
		description		: "Merchants of the human city in central Antonica.",
		howToRaise		: "Turn in <a href='http://everquest.allakhazam.com/db/quest.html?quest=262'>orc</a> or <a href='http://everquest.allakhazam.com/db/quest.html?quest=263'>gnoll</a> scalps.",
		factionsLowered	: null,
	},
	//	109
	{
		name			: "Merchants of Kaladim",
		era				: 0,
		importance		: 2,
		allies			: [84,113,162],
		enemies			: [114],
		description		: "Merchants of the dwarf city on Faydwer.",
		howToRaise		: "Bring <a href='http://everquest.allakhazam.com/db/quest.html?quest=642'>Tumpy Tonics</a> to Trantor Everhot.",
		factionsLowered	: [31],
	},
	//	110
	{
		name			: "Merchants of Oggok",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Merchants of the ogre city on Antonica. As this faction has no quests and merchants cannot be killed it's impossible to determine allies and enemies.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	111
	{
		name			: "Merchants of Qeynos",
		era				: 0,
		importance		: 2,
		allies			: [6,26,70],
		enemies			: [17],
		description		: "Merchants of the human city in western Antonica. Not a difficult faction to raise, but also easy to hurt if working on improving some of the shadier factions.",
		howToRaise		: "The most straightforward way is to lay waste to Blackburrow, but if you prefer to stay friendly with the gnolls you can <a href='http://everquest.allakhazam.com/db/quest.html?quest=130'>bring Tumpy Tonics to Groflah Steadirt</a>.",
		factionsLowered	: [146],
	},
	//	112
	{
		name			: "Merchants of Rivervale",
		era				: 0,
		importance		: 2,
		allies			: [42,69,102],
		enemies			: [27],
		description		: "Merchants of the halfling city in central Antonica.",
		howToRaise		: "Deliver bandages to <a href='http://everquest.allakhazam.com/db/quest.html?quest=657'>to Joogl Honeybugger</a>.",
		factionsLowered	: [27],
	},
	//	113
	{
		name			: "Miners Guild 249",
		era				: 0,
		importance		: 2,
		allies			: [23,84,162],
		enemies			: null,
		description		: "Dwarven miners in the mines of Kaladim.",
		howToRaise		: "Deliver <a href='http://everquest.allakhazam.com/db/quest.html?quest=366'>bone chips</a> to Gunlok Jure.",
		factionsLowered	: null,
	},
	//	114
	{
		name			: "Miners Guild 628",
		era				: 0,
		importance		: 2,
		allies			: [42],
		enemies			: [15,17,53],
		description		: "Kaladim rogue guild. Whether by questing or killing, it appears to be impossible to raise this faction without harming the unimportant Butcherblock Bandits faction and vice versa.",
		howToRaise		: "Fight Butcherblock bandits.",
		factionsLowered	: [15],
	},
	//	115
	{
		name			: "Minions of Underfoot",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Elementals and other creatures found within the Ruins of Old Paineel.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	116
	{
		name			: "Mucktail Gnolls",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: [77,82,83],
		description		: "A clan of gnolls found in the area around Highpass.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	117
	{
		name			: "Nagafen",
		era				: 0,
		importance		: 0,
		allies			: [175],
		enemies			: null,
		description		: "The famous fire dragon and his followers living in the caves below Lavastorm.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	118
	{
		name			: "Najena",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "The well known dark elf spellcaster and her followers within the dungeon that bears her name.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	119
	{
		name			: "Neriak Ghoul",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Ghouls guarding the Lodge of the Dead in Neriak.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	120
	{
		name			: "Neriak Ogre",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Ogres living within the dark elf city.",
		howToRaise		: "The only way to raise this faction is to <a href='http://everquest.allakhazam.com/db/quest.html?quest=291'>deliver preserved frog legs to The Gobbler</a>. At +5 faction per turn in this will take quite a few trips from Oggok to Neriak.",
		factionsLowered	: null,
	},
	//	121
	{
		name			: "Neriak Troll",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Trolls living within the dark elf city. Though there is <a href='http://everquest.allakhazam.com/db/quest.html?quest=4018'>a quest</a> that increases it, it is reportedly restricted to trolls only so I'm treating this faction as unincreasible for the purposes of this guide.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	122
	{
		name			: "Oggok Guards",
		era				: 0,
		importance		: 2,
		allies			: [25],
		enemies			: null,
		description		: "Ogre city guards.",
		howToRaise		: "Help the ogres <a href='http://everquest.allakhazam.com/db/quest.html?quest=2473'>exterminate vermin</a>. If you don't fancy slaughtering countless armadillos you can also do Clurg quests like <a href='http://everquest.allakhazam.com/db/quest.html?quest=290'>pickled froglok</a> at the expense of Kazon Stormhammer faction.",
		factionsLowered	: [84],
	},
	//	123
	{
		name			: "Oggok Resident",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Ogre citizens.",
		howToRaise		: "The only way to increase this faction is by completing <a href='http://everquest.allakhazam.com/db/quest.html?quest=278'>this quest</a>. Killing the slayers will wreck DaBashers faction, but the drops are tradeable so this can be avoided.",
		factionsLowered	: [35],
	},
	//	124
	{
		name			: "Opal Darkbriar",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	125
	{
		name			: "Oracle of K'Arnon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	126
	{
		name			: "Order of Three",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	127
	{
		name			: "Paladins of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	128
	{
		name			: "Paladins of Underfoot",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	129
	{
		name			: "Peace Keepers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	130
	{
		name			: "Phinigel Autropos",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	131
	{
		name			: "Pickclaw Goblins",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	132
	{
		name			: "Pirates of the Pine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	133
	{
		name			: "Pixies of Faydwer",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	134
	{
		name			: "Priest of Innoruuk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	135
	{
		name			: "Priests of Life",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	136
	{
		name			: "Priests of Marr",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	137
	{
		name			: "Priests of Mischief",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	138
	{
		name			: "Primordial Malice",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	139
	{
		name			: "Protectors of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	140
	{
		name			: "Protectors of Pine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	141
	{
		name			: "Qeynos Citizens",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	142
	{
		name			: "Qeynos Elite Watch",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	143
	{
		name			: "Residents of Jaggedpine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	144
	{
		name			: "Riptide Goblins",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	145
	{
		name			: "Rogues of the White Rose",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	146
	{
		name			: "Sabertooths of Blackburrow",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	147
	{
		name			: "Shadowed Men",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	148
	{
		name			: "Shadowknights of Night Keep",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	149
	{
		name			: "Shaman of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	150
	{
		name			: "Shamen of Justice",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	151
	{
		name			: "Shamen of War",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	152
	{
		name			: "Shralok Orcs",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	153
	{
		name			: "Silent Fist Clan",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	154
	{
		name			: "Sky Talons",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	155
	{
		name			: "Soldiers of Tunare",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	156
	{
		name			: "Solusek Mining Co.",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	157
	{
		name			: "Song Weavers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	158
	{
		name			: "Split Paw Clan",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	159
	{
		name			: "Sporali",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	160
	{
		name			: "Steel Warriors",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	161
	{
		name			: "Stone Hive Bixies",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	162
	{
		name			: "Storm Guard",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	163
	{
		name			: "Storm Reapers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	164
	{
		name			: "Surefall Protected Animals",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	165
	{
		name			: "Temple of Solusek Ro",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	166
	{
		name			: "The Dead",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	167
	{
		name			: "The Freeport Milita",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	168
	{
		name			: "The Spurned",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	169
	{
		name			: "Treants of Jaggedpine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	170
	{
		name			: "Tribe Vrodak",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [64],
		description		: "Kobolds living in Lavastorm and the adjacent caverns. Diametrically opposed to Goblins of Fire Peak. You can raise one or the other but not both.",
		howToRaise		: "Kill nearby cinder goblins.",
		factionsLowered	: [64],
	},
	//	171
	{
		name			: "Tunare's Scouts",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	172
	{
		name			: "Undead Frogloks of Guk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	173
	{
		name			: "Unkempt Druids",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	174
	{
		name			: "Verish Mal",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	175
	{
		name			: "Vox",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	176
	{
		name			: "Warriors of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	177
	{
		name			: "Whistling Fist Brotherhood",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	178
	{
		name			: "Wizards of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	179
	{
		name			: "Wolves of the North",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	180
	{
		name			: "Zazamoukh",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [5],
		description		: "A sphinx and her scarab followers found in Rathe Mountains.",
		howToRaise		: "Kill the rival sphinx Ankhefenmut and her followers.",
		factionsLowered	: [5],
	},
	//	181
	{
		name			: "Betrayers of Di'Zok",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	182
	{
		name			: "Bloodgills",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	183
	{
		name			: "Brood of Di'Zok",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	184
	{
		name			: "Brood of Kotiz",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	185
	{
		name			: "Burynai Legion",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	186
	{
		name			: "Cabilist Residents",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	187
	{
		name			: "Citizens of Torsis",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	188
	{
		name			: "Crusaders of Greenmist",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	189
	{
		name			: "Drusella Sathir",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	190
	{
		name			: "Followers of Korocust",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	191
	{
		name			: "Frogloks of Krup",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	192
	{
		name			: "Frogloks of Kunark",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	192
	{
		name			: "Frogloks of Sebilis",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	193
	{
		name			: "Goblins of Cleaving Tooth",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	194
	{
		name			: "Goblins of Mountain Death",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	195
	{
		name			: "Horde of Xalgoz",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	196
	{
		name			: "Inhabitants of Firiona Vie",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	197
	{
		name			: "Legion of Cabilis",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	198
	{
		name			: "Minions of Scale",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	199
	{
		name			: "Pack of Tomar",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	200
	{
		name			: "Pirates of Gunthak",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	201
	{
		name			: "Ring of Scale",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	202
	{
		name			: "Sarnak Collective",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	203
	{
		name			: "Scaled Mystics",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	204
	{
		name			: "Spirocs of Timorous",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	205
	{
		name			: "Swift Tails",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	206
	{
		name			: "Syrik Iceblood",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	207
	{
		name			: "The Forsaken",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	208
	{
		name			: "The Hotwingz",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	209
	{
		name			: "The Kromdek",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	210
	{
		name			: "The Kromdul",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	211
	{
		name			: "Thrall of Kyl",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	212
	{
		name			: "Trakanon",
		era				: 1,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "The infamous undead dragon living in Sebilis. While it is possible to raise this faction, doing so would ruin the irreperable Jaled Dar faction as well as Claws of Veeshan and Ring of Scale, so it may not be worth the trouble unless you really like Trakanon.",
		howToRaise		: "Kill Jaled Dar's shade in Dragon Necropolis.",
		factionsLowered	: null,
	},
	//	213
	{
		name			: "Truespirit",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	214
	{
		name			: "Venril Sathir",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	215
	{
		name			: "Zordak Ragefire",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	216
	{
		name			: "Clan Grikbar",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [63],
		description		: "Kobolds found in Steamfont Mountains, ostensibly. This faction is not included in the in game faction window and the Grikbar kobolds in Steamfont appear to longer be part of it. Though it can be increased by killing Gem Choppers there is no benefit to doing so, not even being non-KOS or having a nice full bar in your faction window.",
		howToRaise		: "Kill Gem Choppers.",
		factionsLowered	: [63],
	},
	//	217
	{
		name			: "Queen Cristnaos Thex",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: null,
		description		: "The queen of the dark elves, opposed to several other Neriak factions, including the dark elf king's faction. This faction is not included in the in game faction window and doesn't appear to have any NPCs associated with it. It can be raised, but doesn't appear to carry any benefit to doing so, not even being non-KOS or having a full bar in the faction window.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	218
	{
		name			: "",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},

];