//This would probably make more sense as a SQL table but github.io doesn't support PHP so here we are.

var factionList = [
	//	0
	{
		name			: "Agents of Mistmoore",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Servants of the famous vampire found in his Faydwer castle, as well as his Drachnid agents in Kunark.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	1
	{
		name			: "Aggressors of Kithicor",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	2
	{
		name			: "Allize Taeew",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: "Cannibalistic lizardmen found in the Feerrott.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	3
	{
		name			: "Allize Volew",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [2],
		description		: "One of two clans of Lizardmen found in the Feerrott and Rathe Mountains.",
		howToRaise		: "Slaughter the rival lizardmen of the Tae Ew clan, found throughout the Feerrott.",
		factionsLowered	: [2],
	},
	//	4
	{
		name			: "Anchorites of Brell Serilis",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: null,
		description		: "Gnoll worshippers of Brell Serilis found in the Jaggedpine Forest",
		howToRaise		: "Complete the quest <a href='http://everquest.allakhazam.com/db/quest.html?quest=2176'>Snarla's friendship</a>.",
		factionsLowered	: null,
	},
	//	5
	{
		name			: "Ankhefenmut",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [180],
		description		: "A sphinx and her scarab followers found in Rathe Mountains.",
		howToRaise		: "Kill the rival sphinx Zazamoukh and her followers.",
		factionsLowered	: [180],
	},
	//	6
	{
		name			: "Antonius Bayle",
		era				: 0,
		importance		: 2,
		allies			: [70,111],
		enemies			: [81,202],
		description		: "The leader of the city of Qeynos and some of his agents.",
		howToRaise		: "Many quests in Qeynos will increase this faction. The easiest repeatable way is probably <a href='http://everquest.allakhazam.com/db/quest.html?quest=574'>giving bone chips to Lashun Novashine</a>.",
		factionsLowered	: [11],
	},
	//	7
	{
		name			: "Arboreans of the Faydark",
		era				: 0,
		importance		: 1,
		allies			: null,
		enemies			: [55,155,60,171],
		description		: "Small treants found in the greater Faydark. This faction is listed as Unimportant as it starts out non-KOS, but killing them does give boosts to some Kelethin factions so you may wish to treat this faction as expendable.",
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	8
	{
		name			: "Arcane Scientists",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	9
	{
		name			: "Ashen Order",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	10
	{
		name			: "Befallen Inhabitants",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	11
	{
		name			: "Bloodsabers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	12
	{
		name			: "Broken Skull Clan",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	13
	{
		name			: "Brownies of Faydwer",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	14
	{
		name			: "Burning Dead",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	15
	{
		name			: "Butcherblock Bandits",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	16
	{
		name			: "Carson McCabe",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	17
	{
		name			: "Circle of Unseen Hands",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	18
	{
		name			: "Citizens of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	19
	{
		name			: "Clan Kolbok",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	20
	{
		name			: "Clan Runnyeye",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	21
	{
		name			: "Clerics of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	22
	{
		name			: "Clerics of Tunare",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	23
	{
		name			: "Clerics of Underfoot",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	24
	{
		name			: "Clockworks of Ak'Anon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	25
	{
		name			: "Clurg",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	26
	{
		name			: "Coalition of Tradefolk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	27
	{
		name			: "Coalition of Tradefolk Underground",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	28
	{
		name			: "Commons Residents",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	29
	{
		name			: "Corrupt Qeynos Guards",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	30
	{
		name			: "Craftkeepers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	31
	{
		name			: "Craknek Warriors",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	32
	{
		name			: "Crimson Hands",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	33
	{
		name			: "Crushbone Orcs",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	34
	{
		name			: "Cursed Frogloks of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	35
	{
		name			: "DaBashers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	36
	{
		name			: "Dark Bargainers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	37
	{
		name			: "Dark Ones",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	38
	{
		name			: "Dark Reflection",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	39
	{
		name			: "Darkpaws of Jaggedpine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	40
	{
		name			: "Deathfist Orcs",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	41
	{
		name			: "Deepmuses",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	42
	{
		name			: "Deeppockets",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	43
	{
		name			: "Deepwater Knights",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	44
	{
		name			: "Defective Clockwork",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	45
	{
		name			: "Defenders of Kithicor",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	46
	{
		name			: "Dervish Cutthroats",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	47
	{
		name			: "Dismal Rage",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	48
	{
		name			: "Donovon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	49
	{
		name			: "Drafling",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	50
	{
		name			: "Dreadguard Inner",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	51
	{
		name			: "Dreadguard Outer",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	52
	{
		name			: "Dryads of the Grove",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	53
	{
		name			: "Ebon Mask",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	54
	{
		name			: "Eldritch Collective",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	55
	{
		name			: "Emerald Warriors",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	56
	{
		name			: "Erudin Citizens",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	57
	{
		name			: "Exiled Frogloks",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	58
	{
		name			: "Fairie",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	59
	{
		name			: "Fallen of Bloody Kithicor",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	60
	{
		name			: "Faydarks Champions",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	61	
	{
		name			: "Frogloks of Guk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	62
	{
		name			: "Gate Callers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	63
	{
		name			: "Gem Choppers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	64
	{
		name			: "Goblins of Fire Peak",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	65
	{
		name			: "Green Blood Knights",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	66
	{
		name			: "Grobb Guard",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	67
	{
		name			: "Grobb Merchants",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	68
	{
		name			: "Guardians of the Hatchling",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	69	
	{
		name			: "Guardians of the Vale",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	70
	{
		name			: "Guards of Qeynos",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	71
	{
		name			: "Guktan Elders",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	72
	{
		name			: "Guktan Suppliers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	73
	{
		name			: "Heretics",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	74
	{
		name			: "High Council of Erudin",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	75
	{
		name			: "High Council of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	76
	{
		name			: "High Guard of Erudin",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	77
	{
		name			: "Highpass Guards",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	78
	{
		name			: "Indigo Brotherhood",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	79
	{
		name			: "Inhabitants of Hate",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	80
	{
		name			: "Jaggedpine Treefolk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	81
	{
		name			: "Kane Bayle",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	82
	{
		name			: "Karana Bandits",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	83
	{
		name			: "Karana Residents",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	84
	{
		name			: "Kazon Stormhammer",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	85
	{
		name			: "Keepers of the Arts",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	86
	{
		name			: "Kejek Village",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	87
	{
		name			: "Kelethin Merchants",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	88
	{
		name			: "Kerra Isle",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	89
	{
		name			: "Kerra of Barren Coast",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	90
	{
		name			: "King Ak'Anon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	91
	{
		name			: "King Naythox Thex",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	92
	{
		name			: "King Tearis Thex",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	93
	{
		name			: "King Xorbb",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	94
	{
		name			: "Kithicor Residents",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	95
	{
		name			: "Knights of Thunder",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	96
	{
		name			: "Knights of Truth",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	97
	{
		name			: "Kobolds of Fire Pit",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	98
	{
		name			: "Krag",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	99
	{
		name			: "League of Antonican Bards",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	100
	{
		name			: "Lorekeepers of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	101
	{
		name			: "Mayong Mistmoore",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	102
	{
		name			: "Mayor Gubbin",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	103
	{
		name			: "Meldrath",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	104
	{
		name			: "Merchants of Ak'Anon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	105
	{
		name			: "Merchants of Erudin",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	106
	{
		name			: "Merchants of Felwithe",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	107
	{
		name			: "Merchants of Halas",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	108
	{
		name			: "Merchants of Highpass",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	109
	{
		name			: "Merchants of Kaladim",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	110
	{
		name			: "Merchants of Oggok",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	111
	{
		name			: "Merchants of Qeynos",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	112
	{
		name			: "Merchants of Rivervale",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	113
	{
		name			: "Miners Guild 249",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	114
	{
		name			: "Miners Guild 628",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	115
	{
		name			: "Minions of Underfoot",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	116
	{
		name			: "Mucktail Gnolls",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	117
	{
		name			: "Nagafen",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	118
	{
		name			: "Najena",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	119
	{
		name			: "Neriak Ghoul",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	120
	{
		name			: "Neriak Ogre",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	121
	{
		name			: "Neriak Troll",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	122
	{
		name			: "Oggok Guards",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	123
	{
		name			: "Oggok Resident",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	124
	{
		name			: "Opal Darkbriar",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	125
	{
		name			: "Oracle of K'Arnon",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	126
	{
		name			: "Order of Three",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	127
	{
		name			: "Paladins of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	128
	{
		name			: "Paladins of Underfoot",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	129
	{
		name			: "Peace Keepers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	130
	{
		name			: "Phinigel Autropos",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	131
	{
		name			: "Pickclaw Goblins",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	132
	{
		name			: "Pirates of the Pine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	133
	{
		name			: "Pixies of Faydwer",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	134
	{
		name			: "Priest of Innoruuk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	135
	{
		name			: "Priests of Life",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	136
	{
		name			: "Priests of Marr",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	137
	{
		name			: "Priests of Mischief",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	138
	{
		name			: "Primordial Malice",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	139
	{
		name			: "Protectors of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	140
	{
		name			: "Protectors of Pine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	141
	{
		name			: "Qeynos Citizens",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	142
	{
		name			: "Qeynos Elite Watch",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	143
	{
		name			: "Residents of Jaggedpine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	144
	{
		name			: "Riptide Goblins",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	145
	{
		name			: "Rogues of the White Rose",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	146
	{
		name			: "Sabertooths of Blackburrow",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	147
	{
		name			: "Shadowed Men",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	148
	{
		name			: "Shadowknights of Night Keep",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	149
	{
		name			: "Shaman of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	150
	{
		name			: "Shamen of Justice",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	151
	{
		name			: "Shamen of War",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	152
	{
		name			: "Shralok Orcs",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	153
	{
		name			: "Silent Fist Clan",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	154
	{
		name			: "Sky Talons",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	155
	{
		name			: "Soldiers of Tunare",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	156
	{
		name			: "Solusek Mining Co.",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	157
	{
		name			: "Song Weavers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	158
	{
		name			: "Split Paw Clan",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	159
	{
		name			: "Sporali",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	160
	{
		name			: "Steel Warriors",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	161
	{
		name			: "Stone Hive Bixies",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	162
	{
		name			: "Storm Guard",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	163
	{
		name			: "Storm Reapers",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	164
	{
		name			: "Surefall Protected Animals",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	165
	{
		name			: "Temple of Solusek Ro",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	166
	{
		name			: "The Dead",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	167
	{
		name			: "The Freeport Milita",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	168
	{
		name			: "The Spurned",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	169
	{
		name			: "Treants of Jaggedpine",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	170
	{
		name			: "Tribe Vrodak",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	171
	{
		name			: "Tunare's Scouts",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	172
	{
		name			: "Undead Frogloks of Guk",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	173
	{
		name			: "Unkempt Druids",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	174
	{
		name			: "Verish Mal",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	175
	{
		name			: "Vox",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	176
	{
		name			: "Warriors of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	177
	{
		name			: "Whistling Fist Brotherhood",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	178
	{
		name			: "Wizards of Gukta",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	179
	{
		name			: "Wolves of the North",
		era				: 0,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	180
	{
		name			: "Zazamoukh",
		era				: 0,
		importance		: 2,
		allies			: null,
		enemies			: [5],
		description		: "A sphinx and her scarab followers found in Rathe Mountains.",
		howToRaise		: "Kill the rival sphinx Ankhefenmut and her followers.",
		factionsLowered	: [5],
	},
	//	181
	{
		name			: "Betrayers of Di'Zok",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	182
	{
		name			: "Bloodgills",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	183
	{
		name			: "Brood of Di'Zok",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	184
	{
		name			: "Brood of Kotiz",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	185
	{
		name			: "Burynai Legion",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	186
	{
		name			: "Cabilist Residents",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	187
	{
		name			: "Citizens of Torsis",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	188
	{
		name			: "Crusaders of Greenmist",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	189
	{
		name			: "Drusella Sathir",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	190
	{
		name			: "Followers of Korocust",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	191
	{
		name			: "Frogloks of Krup",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	192
	{
		name			: "Frogloks of Kunark",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	192
	{
		name			: "Frogloks of Sebilis",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	193
	{
		name			: "Goblins of Cleaving Tooth",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	194
	{
		name			: "Goblins of Mountain Death",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	195
	{
		name			: "Horde of Xalgoz",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	196
	{
		name			: "Inhabitants of Firiona Vie",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	197
	{
		name			: "Legion of Cabilis",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	198
	{
		name			: "Minions of Scale",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	199
	{
		name			: "Pack of Tomar",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	200
	{
		name			: "Pirates of Gunthak",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	201
	{
		name			: "Ring of Scale",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	202
	{
		name			: "Sarnak Collective",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	203
	{
		name			: "Scaled Mystics",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	204
	{
		name			: "Spirocs of Timorous",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	205
	{
		name			: "Swift Tails",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	206
	{
		name			: "Syrik Iceblood",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	207
	{
		name			: "The Forsaken",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	208
	{
		name			: "The Hotwingz",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	209
	{
		name			: "The Kromdek",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	210
	{
		name			: "The Kromdul",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	211
	{
		name			: "Thrall of Kyl",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	212
	{
		name			: "Trakanon",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	213
	{
		name			: "Truespirit",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	214
	{
		name			: "Venril Sathir",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	215
	{
		name			: "Zordak Ragefire",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},
	//	
	{
		name			: "",
		era				: 1,
		importance		: 0,
		allies			: null,
		enemies			: null,
		description		: null,
		howToRaise		: null,
		factionsLowered	: null,
	},

];